### ISSUE TITLE
[3x7h] - vertical layout component

### ISSUE THREAD

**Issue by adrianjost** [hpi-swa-teaching/SWT18-Project-08#12]
~make it possible to place components horizontally next to each other. You should select how many components you wan't in one row and maybe the width of each coloumn. 
Alternatively, you can evenly distribute the columns for the beginning to make it easier.~

~Ideas: +- Button in the top right corner to select the number of coloumns~

**Comment by malte-b** [comment]
-[ ] dynamically resize components
-[ ] "wrap in horizontal layout"
-[ ] append components
-[ ] insert and delete components horizontally, no limits
-[ ] strong emphasized borders where components can be added
