### ISSUE TITLE
[0.25h] Fix Test Class

### ISSUE THREAD

**Issue by tom95** [hpi-swa-teaching/SWT18-Project-08#15]
In order for the testrunner and travis to find your tests, you'll need to make your tests class inherit from TestCase (or PHTestCase/PHEventTestCase). Additionally, it is a requirement to prefix all test methods with `test`, e.g. `testAddMenuButtons`. All other methods are believed to be helper methods and are thus not executed by the testrunner.

**Comment by adrianjost** [comment]
https://github.com/hpi-swa-teaching/SWT18-Project-08/pull/17
