### ISSUE TITLE
[2x2h (+ 3h)] - add text components

### ISSUE THREAD

**Issue by KatharinaBlass** [hpi-swa-teaching/SWT18-Project-08#3]
As a user I would like to add text blocks to my document in order to write my text.

- [x] text area
- [x] text styling
    - [x] bold (inline)
    - [x] kursiv (inline)
    - [x] underlined (inline)
    - [x] striked (inline)

extended by (not part of this issue):
- [ ] #1
- [ ] #2
- [ ] #29

**Comment by rocklegende** [comment]
2 h

**Comment by malte-b** [comment]
Only tests missing right now

**Comment by adrianjost** [comment]
- [ ] write tests
- [ ] popup delete is buggy (sometimes it's not going to hide)
- [ ] merge cconflicts
