### ISSUE TITLE
[2x3.5h] - tidy up menus (buttongroups)

### ISSUE THREAD

**Issue by adrianjost** [hpi-swa-teaching/SWT18-Project-08#47]
- [x] add tooltip to each button
- [x] make UI smaller (less buttons in each row)
- [x] hover over component opens component menus , otherwise they are hidden (optional)

**Comment by adrianjost** [comment]
- [ ] button für verschieben nur anzeigen, wenn möglich (nicht ganz oben)

**Comment by tom95** [comment]
features as seen in the branch seem good!

**Comment by adrianjost** [comment]
ToDo: https://github.com/hpi-swa-teaching/SWT18-Project-08/pull/66
