### ISSUE TITLE
[2h] - picture component

### ISSUE THREAD

**Issue by adrianjost** [hpi-swa-teaching/SWT18-Project-08#5]
As a user I want to add pictures to my document in order to display flowers.

Simply add a picture, no layouting, scaling or similar things!

 - [x] click on "add image component" inserts an image 
 - [x] by path (input field) 
 - [x] as the only visible component

**Comment by rocklegende** [comment]
max 1h

**Comment by tom95** [comment]
Missing tests, new checklist for next week:
- [ ] on click a filepicker is opened
- [ ] if the filepicker is closed nothing happens
- [ ] if an image is accepted it is added as the last/only component
- [ ] all necessary steps are tested

**Comment by KatharinaBlass** [comment]
2 h

**Comment by adrianjost** [comment]
@tom95 Wie können wir Icons mit Bindestrich im Namen nutzen? Beispielsweise [dieses](https://fontawesome.com/icons/file-image?style=solid)

**Comment by adrianjost** [comment]
- --> _

3h needed for now. Except the first all tests are still missing.

**Comment by adrianjost** [comment]
+ 2h
#21
