### ISSUE TITLE
[2x4h] - export document to markdown

### ISSUE THREAD

**Issue by adrianjost** [hpi-swa-teaching/SWT18-Project-08#59]
- [x] only export to markdown (no import!)
- [x] horizontal  will be displayed vertical

**Comment by pauludobeneke97** [comment]
- [ ] AddComponent
 - [ ] ImageComponent
 - [ ] VerticalLayoutComponent
 - [ ] HorizontalComponent
 - [ ] TextComponent (text only)
 - [ ] TextComponent (with text highlight)
 - [ ] CodeComponent
 - [ ] HeaderComponent
 - [ ] RichTextEditor
