### ISSUE TITLE
[1x1h] Change default font to ttcfont

### ISSUE THREAD

**Issue by malte-b** [hpi-swa-teaching/SWT18-Project-08#70]
- [ ] make FontSizeField usable to be able to change the actual displayed font size for any allowed number that is put in

**Comment by malte-b** [comment]
Should already work at least in code component as we don't use a standard font there, but it still isn't working, so I won't be able to fix the issue this week as the problem seems to be a different one as I thought

**Comment by adrianjost** [comment]
ping @malte-b 
Is this solved with the new font import?

**Comment by malte-b** [comment]
yes as i mentioned in the pull request
