### ISSUE TITLE
[3h] - create main architecture

### ISSUE THREAD

**Issue by KatharinaBlass** [hpi-swa-teaching/SWT18-Project-08#8]
Wished available functions:
1. button bar of available components
2. document that could accept components
3. Discuss main layout idea (row based, free positioning, ...)
4. Discuss components api (available functions, variables, ... that every Component should implement)

- [x] abstract super class for components
- [x] (thus far empty) button bar for adding components
- [x] empty document that has an API to add a component

**Comment by rocklegende** [comment]
3.5 h

**Comment by tom95** [comment]
- [ ] existing components (image, menu) are ported to pheno
- [ ] define a component class that may contain a pheno widget
- [ ] allow deleting a component
