### ISSUE TITLE
Enable linux for travis again after it's updated to support SSL

### ISSUE THREAD

**Issue by malte-b** [hpi-swa-teaching/SWT18-Project-08#94]
The old Squeak VM does not support SSL requests to GitHub.com. We have decided to disable Linux builds because of this. Re-enable Linux build once the Linux VM has been updated.

**Comment by fniephaus** [comment]
I've updated all VMs smalltalkCI uses across all Squeak builds: https://github.com/hpi-swa/smalltalkCI/issues/382.
